name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "helm/**"

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        id: cr
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: helm
          packages_dir: cr-packages
          release_name: timesheet-filler

      - name: Package and Release Charts
        run: |
          # Package the chart
          helm package helm/timesheet-filler -d cr-packages

          # Upload the chart as a GitHub release
          cr upload -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} -p cr-packages

          # Update the index.yaml on gh-pages branch
          cr index -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} -p cr-packages -c https://$GITHUB_SERVER/$GITHUB_REPOSITORY/

      - name: Push index.yaml to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cr-index
          publish_branch: gh-pages
