name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "helm/**"

permissions:
  contents: write
  pages: write
  packages: write

jobs:
  release:
    name: Release Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for chart-releaser to work properly

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Add Helm repositories
        run: |
          # Add any required helm repositories here if your chart has dependencies
          # Example: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Release Helm Charts
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: helm
          # config: cr.yaml

      - name: Verify Chart Release
        run: |
          echo "Verifying chart was published successfully"
          curl -s https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml | grep "timesheet-filler"
