name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            **/go.sum
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o excelapp

      - name: Test application
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t yourusername/excelapp:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push yourusername/excelapp:${{ github.sha }}

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v2.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install excelapp helm/excelapp \
            --set image.tag=${{ github.sha }} \
            --set image.repository=yourusername/excelapp
