name: Release Helm Chart After App Release

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if build was triggered by version tag
        id: check_tag
        run: |
          # Get the head_ref or head_sha from the triggering workflow
          HEAD_SHA="${{ github.event.workflow_run.head_sha }}"
          echo "Workflow was triggered by commit: $HEAD_SHA"

          # Find tags pointing to this commit
          TAGS=$(git tag --points-at $HEAD_SHA)
          echo "Tags on this commit: $TAGS"

          # Check if any of those tags match our version pattern
          VERSION_TAG=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          if [ -n "$VERSION_TAG" ]; then
            echo "Found version tag: $VERSION_TAG"
            echo "is_version_tag=true" >> $GITHUB_OUTPUT
            echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
            VERSION=${VERSION_TAG#v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "helm_tag=helm-$VERSION_TAG" >> $GITHUB_OUTPUT
          else
            echo "No version tag found on this commit."
            echo "is_version_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Chart Versions
        if: steps.check_tag.outputs.is_version_tag == 'true'
        run: |
          APP_VERSION="${{ steps.check_tag.outputs.version }}"
          CHART_VERSION="${{ steps.check_tag.outputs.version }}"

          echo "Updating chart to version $CHART_VERSION and appVersion $APP_VERSION"

          # Update Chart.yaml
          CHART_PATH="helm/timesheet-filler/Chart.yaml"
          sed -i "s/^version:.*/version: $CHART_VERSION/" $CHART_PATH
          sed -i "s/^appVersion:.*/appVersion: \"$APP_VERSION\"/" $CHART_PATH

          echo "Updated Chart.yaml:"
          cat $CHART_PATH

          # Commit the changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $CHART_PATH
          git commit -m "Update Helm chart version to $CHART_VERSION [skip ci]"
          git push origin HEAD:main

      - name: Create Helm Chart Tag
        if: steps.check_tag.outputs.is_version_tag == 'true'
        run: |
          HELM_TAG="${{ steps.check_tag.outputs.helm_tag }}"

          echo "Creating Helm chart tag: $HELM_TAG"

          # Check if tag already exists
          if git tag | grep -q "^$HELM_TAG$"; then
            echo "Tag $HELM_TAG already exists. Skipping tag creation."
          else
            # Create and push tag
            git tag $HELM_TAG
            git push origin $HELM_TAG
            echo "Created and pushed tag: $HELM_TAG"
          fi
